### ISSUE TITLE
can not train using multi GPUs

### ISSUE THREAD

**Issue by thangckt** [MDIL-SNU/SevenNet#118]
hi @YutackPark 

I found some problem with ver 0.10

1. Can not run when using multi GPUs

I try with various options, and the time like this:
- Using 1 CPU, Epoch 1 elapsed: 0:42:14.34
- Using 1 CPU + 1 GPU, Epoch 1 elapsed: 1:05:01.08
- Using 2 CPU + 2 GPU, interrupt with error
```
  File "/python3.11/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 1157, in next_rendezvous
    self._op_executor.run(join_op, deadline, self._get_deadline)
  File "/python3.11/site-packages/torch/distributed/elastic/rendezvous/dynamic_rendezvous.py", line 679, in run
    raise RendezvousTimeoutError
torch.distributed.elastic.rendezvous.api.RendezvousTimeoutError
```
It seemly that using GPU does not have better performance.

2. The key `data_divide_ratio` does not work
When setting this key, no validset is created

Can you have some guide?
Thank you so much.

**Comment by YutackPark** [comment]
Could you share the input scripts? I have tested and trained multi-GPU
setup with the same version (up to 4~6) gpus.

Data divide by ratio is temporarily omitted for the new version. I will
make it back soon for newer version. You can still turn old version with -m
train_v1 arms with 'sevenn'

2024년 10월 31일 (목) 오후 3:03, C. Thang Nguyen ***@***.***>님이 작성:

**Comment by thangckt** [comment]
> You can still turn old version with -m
train_v1 arms with 'sevenn'

The old vers does not work well with stress as we discussed before.
I attached the input file I used and the lc.csv
With that input and lc, can you give some advice to modify input parameters so that it can optimize the tranning time.

Thank you os much.

[input.txt](https://github.com/user-attachments/files/17595130/input.txt)
[lc.csv](https://github.com/user-attachments/files/17595132/lc.csv)

**Comment by YutackPark** [comment]
I couldn't reproduce the error. Here's the log with 2 GPUs with the same inputs but only `data_format_args`
[log1.sevenn.txt](https://github.com/user-attachments/files/17595840/log1.sevenn.txt)

For your concerns in the performance, your model and batch size is very small to saturate GPU card. While it depends on which GPU you actually use, but it is still too small, especially batch size. To fully utilize GPU, you should increase batch_size as much as possible before the out of memory error from the GPU, and the maximum number of batch size is inversly proportional to model parameters.

For the timeout error in your multi-GPU setup... have you tried to load generated `.pt` file directly to avoid preprocess steps? I think it is either in data set or your GPU cluster.

**Comment by thangckt** [comment]
hi @YutackPark 
Many thanks for your guide.

> your model is very small

I have only 5 chemical elements in the system, and want to keep the model as small as possible to optimize inference performance. Do you have any basic rule to choose model's parameters, especially these ones:
```yml
channel: 4                                  
lmax: 1                                  
num_convolution_layer: 4               
weight_nn_hidden_neurons: [64, 64]
```

> increase batch_size as much as possible

can you have a little guide how to check how fit batch_size to GPU's memory?

> the cause is either in data set or your GPU cluster

I will check this 

Many thanks.

**Comment by thangckt** [comment]
> the cause is either in data set or your GPU cluster

I think that no matter with those two. 

Let me summarize sth I tried with:
- Sevenn ver: lastest main branch
- train cmd: `torchrun --standalone --nnodes {number of nodes} --nproc_per_node {number of GPUs} --no_python ...`

Observation:
- 1 cpu + 1 gpu: code run as expected
- 1 cpu + 2 gpu: graph_build twice (very slow), then the training run as expected
- 2 cpu + 2 gpu: code hanged, the graph_buidl can not executed.

I then tried to build graph separately, and pass file `/sevenn_data/graph.pt`, then got error:
```
/site-packages/sevenn/train/graph_dataset.py", line 184, in __init__
[rank0]:     super().__init__(
[rank0]:   File "/site-packages/torch_geometric/data/in_memory_dataset.py", line 81, in __init__
[rank0]:     super().__init__(root, transform, pre_transform, pre_filter, log,
[rank0]:   File "/site-packages/torch_geometric/data/dataset.py", line 115, in __init__
[rank0]:     self._process()
[rank0]:   File "/site-packages/torch_geometric/data/dataset.py", line 262, in _process
[rank0]:     self.process()
[rank0]:   File "/site-packages/sevenn/train/graph_dataset.py", line 258, in process
[rank0]:     raise ValueError('Zero graph found after filtering')
[rank0]: ValueError: Zero graph found after filtering
```
May be `torchrun` can not work well with some updates in the process of `graph_build`.
Do you think that it is better saving old legacy version in a separated branch?

Thanks.

**Comment by YutackPark** [comment]
That's interesting, Note that latest main brach is not stable, so it is not released yet (v0.10.1). Here's some questions.

1. How did you controlled number of cpu cores in your experiment?

2. When using more than two gpus, each process build its own graph and run stats => this is a known issue, and gonna be fixed. But 1 cpu core + 2 gpu cards is very uncommon setup and I haven't found performance drop in normal usage (cpu cores >= gpu cards)

3. For zero graph issue, could you share the `sevenn_data/graph.yaml` file?

4.Keeping old version?
=> User can access older version, as I'm not removing old releases in git or pypi. Although the old version is stable and tested, I couldn't maintain it any longer as it is a spaghetti I cooked when I was not used to both python and torch. Sorry for the inconvenience, but also thanks for raising the issue.

**Comment by thangckt** [comment]
> How did you controlled number of cpu cores in your experiment?

I use `torchrun --standalone --nnodes {number of cpus} `

> 1 cpu core + 2 gpu cards is very uncommon setup

Since I can not run with 2 cpu + 2 gpu, so I tried this one, and still gain upto 30 % speed increasing.

> could you share the sevenn_data/graph.yaml file?

this is [graph.txt](https://github.com/user-attachments/files/17606991/graph.txt)

> 4.Keeping old version?

I mean save old version to separated branch to keep your current dev version concise and easier to read. If someone need old version, they just install directly from that branch.

Thank you so much for your help.

**Comment by YutackPark** [comment]
Maybe there's some miscommunication I found. What I mean by CPU is a **CPU core**. Modern computer systems, including my laptop, usually have more than one CPU core. This is different from **nodes** in `torchrun`.  Node refers to physically separated computers, usually available in HPC systems, you should not specify `--nmodes`. It is always one.

`torchrun` will launch two processes as you used `--nproc_per_node 2`, and those process will use two CPU cores or one cores with two threads or something else, it depends on the system.

> this is [graph.txt](https://github.com/user-attachments/files/17606991/graph.txt)

It seems fine. It may not related, but I just merged #119 for better error messages, as I had similar symptoms when I passed wrong path to the updated graph dataset. Could you share `load_***set_path` in your input?

> I mean save old version to separated branch to keep your current dev version concise and easier to read. If someone need old version, they just install directly from that branch.

Indeed, I found the repo has no tag or release for bug fixed v0.9.5. I have created a new branch `v1` right before v0.10.0 merge.

**Comment by thangckt** [comment]
hi @YutackPark 
Many thanks for your instruction.

>What I mean by CPU is a CPU core. Modern computer systems, including my laptop, usually have more than one CPU core. This is different from nodes in `torchrun`

That is the problem. I think this should be noted in the docs.

> Could you share load_***set_path in your input?

```yml
data:
  load_trainset_path:
  - ./sevenn_data/graph.pt
```
This is the error:
```
Processing...
Processing...
... some lines here ...
[rank0]:   File ".../sevenn/train/graph_dataset.py", line 184, in __init__
[rank0]:     super().__init__(
[rank0]:   File ".../torch_geometric/data/in_memory_dataset.py", line 81, in __init__
[rank0]:     super().__init__(root, transform, pre_transform, pre_filter, log,
[rank0]:   File ".../torch_geometric/data/dataset.py", line 115, in __init__
[rank0]:     self._process()
[rank0]:   File ".../torch_geometric/data/dataset.py", line 262, in _process
[rank0]:     self.process()
[rank0]:   File ".../sevenn/train/graph_dataset.py", line 260, in process
[rank0]:     raise ValueError('Zero graph found after filtering')
[rank0]: ValueError: Zero graph found after filtering
E1104 11:36:40.227000 140608456435520 torch/distributed/elastic/multiprocessing/api.py:833] failed (exitcode: 1) local_rank: 0 (pid: 27126) of binary: sevenn
Traceback (most recent call last):
  File "/home/thang/app/conda/miniconda3/envs/py11sevenn/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==2.4.1', 'console_scripts', 'torchrun')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
````

**Comment by thangckt** [comment]
The issue is solved, the remain error maybe another issue. We may close this issue?

Before closing, can you have give some comments on the setting parameters

1. Do you have any "basic rule" to choose parameters for an optimize model? Some of these:
```yml
channel:                                 
lmax:                                 
num_convolution_layer:            
weight_nn_hidden_neurons: 
```
2. The learning curve of my model look like this:
```
epoch,lr,trainset_Energy_RMSE,trainset_Force_RMSE,trainset_Stress_RMSE,trainset_TotalLoss
1,0.005000,2.133584,1.169398,417.788106,2919.443768
2,0.004950,2.135535,1.168351,405.982345,2752.271417
3,0.004901,2.076982,1.148468,367.577886,2244.034427
4,0.004851,1.892421,1.126361,276.875549,1271.986802
5,0.004803,1.835806,1.031304,215.792329,775.775134
6,0.004755,1.811758,0.922248,182.229358,555.006637
```
the error of stress extremely large compare to enery or force. Do you know why?

Thanks.

**Comment by YutackPark** [comment]
> The issue is solved

Nice, about loading .pt file? Could you tell me which was the cause?

> Do you have any "basic rule" to choose parameters for an optimize model? Some of these:
I forgot to mention about it. Firstly, note that our network, except for `self_connection_type: 'linear'`, is same as that of `NequIP`, which has lots of references available in literature.

For me,
```
channel: ?  # depends on complexity of your system. Reasonable default is '32' but there's some experiment that if chemical space is limited, channel can be reduced without losing its accuracy                                
lmax: 1-3  # generally '2', if system is very simple, may '1'. '3' for accurate or or challenging system. If you use '0' it becomes invariat model.                                
num_convolution_layer:  3 to 5  # one or two is not a good option as available tensor product paths are limited.         
weight_nn_hidden_neurons: [64, 64]  # almost always. I have not tested other than this choice
```

> The learning curve of my model look like this:
Little bit high but I think it is still in reasonable range. Stress is logged as kbar unit, which widely used in literature (*10 to get GPa), rather than 'eV/A^3'. In log.sevenn, You can check units of each errors also. I decided to remove units from `.csv` as I found it is very annoying when I wanted to postprocess with it.

**Comment by thangckt** [comment]
Many thanks for instruction on model's parameters.

> Is it about loading .pt file?

Sorry for my not clear expression. It is about "multi GPUs trainning". The remaining prolem is about "loading .pt file" as my last comment. I think it is different from GPUs problem, so it should be discussed in a separated thread.

**Comment by YutackPark** [comment]
> The remaining prolem is about "loading .pt file"

I failed to reproduce your error, with single and two GPUs in my setup. With the input `graph.pt` is generated using `sevenn_graph_build`, and with the current `main` branch;

`data` section of `input_full.yaml`:
```yaml
  data:
      load_trainset_path:
      - ./sevenn_data/graph.pt
      batch_size: 4
```

Two GPU command:
`torchrun --standalone --nproc_per_node 2 --no_python sevenn ./input_full.yaml -d -s`

Single run:
`sevenn input_full.yaml -s`

In both cases training starts successfully with out an error. For the case where dataset path is wrong, program raises an descriptive error that it can not find the file, in both single or two GPU runs.

One thing that I cannot understand is,
```
Processing...
Processing...
```
In your outputs. If there exist single .pt file to load, there should be no `Processing...` printed on output. It is printed when the `PyG` tries to build dataset from scratch, when given path is not a _single pt file_. To debug this case, I need more step by step guideline, that hopefully reproducible with `example_inputs` folder in the SevenNet`, to reproduce it.

One more thing I concern is that, in your `graph.yaml`, I see the path is written like windows filesystem. Are you running your experiments on windows? As `path` is very sensitive between operating systems, and we have not tested our codes on windows, this might be the cause. In this case, also, I need more precise information to reproduce it.

**Comment by thangckt** [comment]
hi @YutackPark 

>Are you running your experiments on windows? 

I build graph on local Win machine, then send .pt to Linux cluster. This could be problem. I will check when I have free cluster resource. 

Thanks.

**Comment by thangckt** [comment]
About this:

> Stress is logged as kbar unit, which widely used in literature (*10 to get GPa), rather than 'eV/A^3'. 

I think It is not good when we have diffrent units on the same table. Maybe better to output quantities in the same units, then the user can convert to their own units when they used?

**Comment by YutackPark** [comment]
> I think It is not good when we have diffrent units on the same table. Maybe better to output quantities in the same units, then users can convert to their own units latter?

Maybe it is one of controversial options if we were at early stage, but unfortunately, it is too late to change the default. However, alternatively, like SevenNet have Stress_GPa error recorder, I think I could implement something like `Stress_eV` error recorder. A user can choose between them. I'll implement this in next release, as it is very straightforward to make.

**Comment by thangckt** [comment]
The default setting will avoid confusion for users. For above example, if you do not inform about unit difference, I will not understand why there is a very large value in one column while very small in others.

Btw, I will happy if you give option for this. And less options are even better :)

Thanks.

**Comment by YutackPark** [comment]
Hi @thangckt , SevenNet already informs units in its `log.sevenn`, which I designed for humans to read. `lc.csv` is just a redundant output I added for convenience, to draw learning curves. As they print exact same values, it is clear to understand. 

The 'same' unit you mentioned is also ambiguous. Energy, force, and stress inherently have different units and they should not be compared with each other to determine whether something seems bigger or not. For example, force error is almost always bigger than energy, but this doesn't necessarily mean that force is not un-trained compared to energy. Therefore, the default unit for stress is a matter of perspective and there is no definite answer. At least in my group, we communicate with kBar units when we mention about stress error, or running MD simulations with SevenNet. This is the reason I choose to use kBar error as a default. I understand that this preference depend on user's background. Therefore I make other error_recorders with different units.

Thanks for your opinions, but we can not change the defaults, as SevenNet already has several users. If we change the defaults, users will have different results with exact same inputs after update. This is the worst thing that can happen for software. Please understand.

Thanks.

**Comment by thangckt** [comment]
Thank @YutackPark

**Comment by thangckt** [comment]
hi @YutackPark 
Can you check the testset path?

The trainning run normally whe only trainset_path is set
```
data:
  load_trainset_path:
  - ./trainset.xyz
```
But when input with testset_path, the code is hung after build graph, but does not throw any error. 
```
data:
  load_trainset_path:
  - ./trainset.xyz
   load_testset_path:
  - ./testset.xyz
```
Can you have a little guide?
Thanks.

**Comment by YutackPark** [comment]
Hi @thangckt , thanks for the report. I tried but couldn't reproduce an error. It is not related to `load_testset_path`, as I'm using it with, without multi-GPU. I also tried using `example_inputs/training`, but it runs without an problem.

I need more context to solve the issue. Are you running this on cluster? If then, could you try to reproduce it in local system, by reducing model parameters and data points?

**Comment by thangckt** [comment]
hi @YutackPark 
I do not have GPU on my local machine, so I can not check.

I am running on Linux remote cluster (Centos 7.8)
The situation is:
- can run with 1 CPU + 1 GPU with `load_trainset_path` + `load_testset_path`
- can run with 2 CPU + 2 GPU with ONLY `load_trainset_path` 
- CAN NOT run with 2 CPU + 2 GPU with `load_trainset_path` + `load_testset_path`. Code hung after build graph

**Comment by YutackPark** [comment]
Multi-GPU failure is more tricky to handle. But, as I'm using `load_trainset_path` + `load_testset_path` with more than 2 GPUs without an issue, I need more information.

1. torchrun --standalone --nnodes=1 --nproc_per_node 2 --no_python sevenn input.yaml -d
Is this the command you used?

2. Have you tried with small model size and batch size? It might be OOM error.

3. Is the error consistent? Especially for GPU nodes, users often share the same node and others incorrectly configured job can interrupt yours.

4. Can you attach: `tail log.sevenn`? I need more specific info.

**Comment by thangckt** [comment]
hi @YutackPark 

> Have you tried with small model size and batch size? It might be OOM error.

This is the problem. There is no oom error is thrown, so I did not think about this. Thank you for your guide.

So there is a problem that there is many RAM required to build graphs, especially on multi processors run.
Do you have any trick to reduce memory?

Thank you for your help.

**Comment by YutackPark** [comment]
Glad you found the root cause

Actually current multiprocess + graph is highly inefficient and should be fixed (#107).
However, if you stuck in graph_build part, I recommend you to preprocess the data with `sevenn_graph_build`. If you already did that, we also have on-the-fly graph build dataset for this case (where graph is too huge to fit memory), but this feature is experimental and not stable.

As a last resort, you can reduce your model's cutoff. It will reduce graph data size in a large margin.

**Comment by thangckt** [comment]
hi @YutackPark 

Thank you for your guide.

>  we also have on-the-fly graph build dataset for this case (where graph is too huge to fit memory), but this feature is experimental and not stable.

It looks exciting.

> However, if you stuck in graph_build part, I recommend you to preprocess the data with `sevenn_graph_build`

Do you think that, it is be better to separate the `graph_build` from the `train` process? I mean you force the users to build graph before training. 
- `sevenn_graph_build` can accept various data types (extxyz,...)
- training only accept `graph.pt`
This will make the code more clear, and remove a lot of confusions as well possible drawbacks

**Comment by YutackPark** [comment]
> Do you think that, it is be better to separate the graph_build from the train process? I mean you force the users to build graph before training.

Thanks for the opinion. Personally, I always prefer to divide this two process. But keeping this feature is also convenient when training data is small. As both of them (sevenn, sevenn_graph_build) share same interface and routines, I think code is not the problem.
